import type { FunnelConfig } from "@/funnels/types";
import {
  fullPostcodeQuestion,
  listedQuestion,
  postcodeAreaQuestion,
  propertyTypeQuestion,
  RESEARCHING,
  specialistCountQuestion,
  timescaleQuestion,
} from "@/funnels/shared";

export const roofingFunnel: FunnelConfig = {
  serviceSlug: "roofing",
  heading: "Roof Replacement",
  researching: { questionId: "timescale", value: RESEARCHING },
  questions: [
    {
      id: "roofType",
      type: "single",
      title: "What kind of roof does your house have?",
      summaryLabel: "Roof type",
      layout: "list",
      options: [
        { value: "pitched-tiles", label: "Sloping, with tiles" },
        { value: "pitched-slate", label: "Sloping, with slate" },
        { value: "flat", label: "Flat roof" },
        { value: "not-sure", label: "Not sure" },
      ],
    },
    postcodeAreaQuestion,
    fullPostcodeQuestion,
    {
      id: "problem",
      type: "multi",
      title: "What's prompting you to look at it?",
      hint: "Choose up to three.",
      summaryLabel: "Reasons",
      max: 3,
      layout: "list",
      options: [
        { value: "leaks", label: "Leaks or damp" },
        { value: "slipped", label: "Slipped, cracked or missing tiles or slates" },
        { value: "sagging", label: "Sagging or uneven roof" },
        { value: "storm", label: "Storm damage" },
        { value: "age", label: "It's old and worn out" },
        { value: "insulation", label: "Improving insulation" },
      ],
    },
    {
      id: "scope",
      type: "single",
      title: "What do you think it needs?",
      summaryLabel: "Work needed",
      layout: "list",
      options: [
        { value: "full", label: "A complete new roof" },
        { value: "part", label: "Part of the roof replacing" },
        { value: "repair", label: "Repairs" },
        { value: "advice", label: "Not sure, I'd like advice" },
      ],
      goodToKnow: {
        when: (v) => v === "full" || v === "part" || v === "advice",
        text: "Replacing a large part of a roof usually needs Building Regulations approval. Roofers registered with a government-authorised scheme can certify their own work; otherwise building control checks it. Your specialist can explain what applies.",
      },
    },
    {
      id: "extras",
      type: "multi",
      title: "Anything else to look at at the same time?",
      hint: "Choose all that apply.",
      summaryLabel: "Also looking at",
      layout: "list",
      options: [
        { value: "roofline", label: "Fascias and soffits" },
        { value: "gutters", label: "Guttering" },
        { value: "chimney", label: "Chimney" },
        { value: "roof-windows", label: "Roof windows" },
        { value: "none", label: "Nothing else" },
      ],
    },
    propertyTypeQuestion,
    {
      id: "storeys",
      type: "single",
      title: "How many storeys is the house?",
      hint: "This helps the specialist plan access, such as scaffolding.",
      summaryLabel: "Storeys",
      options: [
        { value: "1", label: "One" },
        { value: "2", label: "Two" },
        { value: "3+", label: "Three or more" },
        { value: "not-sure", label: "Not sure" },
      ],
    },
    listedQuestion,
    specialistCountQuestion,
    timescaleQuestion,
  ],
};
